spring.application.name=code-analyzer
server.port=9099

# 1. Ollama Configuration
# Ensure you have run 'ollama pull llama3.1' in your terminal
# spring.ai.ollama.base-url=http://localhost:11434
# spring.ai.ollama.chat.options.model=llama3.1
# --- 1. Groq Configuration (Using OpenAI Starter) ---
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=llama-3.1-8b-instant

# --- 2. MCP Client Global Settings ---
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.annotation-scanner.enabled=true