# Project Name and Port
spring.application.name=ollamabasic
server.port=9092

# 1. Ollama Configuration
# Ensure you have run 'ollama pull llama3.1' in your terminal
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.1

# Define the Docling server connection
# Format: spring.ai.mcp.client.stdio.connections.[name].command
spring.ai.mcp.client.annotation-scanner.enabled=true
